// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtYlx21qrWi4Z-hRIwgyESGvCBLrLFsIY',
    appId: '1:248861591273:web:6b0d5a10bbd09fb0a99278',
    messagingSenderId: '248861591273',
    projectId: 'camp-ee562',
    authDomain: 'camp-ee562.firebaseapp.com',
    databaseURL: 'https://camp-ee562-default-rtdb.firebaseio.com',
    storageBucket: 'camp-ee562.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTUxbRMcNwuCP1Cu655_w7B53EsmaikEA',
    appId: '1:248861591273:android:4aea39fdb7dd9682a99278',
    messagingSenderId: '248861591273',
    projectId: 'camp-ee562',
    databaseURL: 'https://camp-ee562-default-rtdb.firebaseio.com',
    storageBucket: 'camp-ee562.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzXc2vPK3awIf7pq_eLMkYclFRx-1ALxU',
    appId: '1:248861591273:ios:b6f0626063150dd0a99278',
    messagingSenderId: '248861591273',
    projectId: 'camp-ee562',
    databaseURL: 'https://camp-ee562-default-rtdb.firebaseio.com',
    storageBucket: 'camp-ee562.firebasestorage.app',
    iosBundleId: 'com.example.camp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzXc2vPK3awIf7pq_eLMkYclFRx-1ALxU',
    appId: '1:248861591273:ios:b6f0626063150dd0a99278',
    messagingSenderId: '248861591273',
    projectId: 'camp-ee562',
    databaseURL: 'https://camp-ee562-default-rtdb.firebaseio.com',
    storageBucket: 'camp-ee562.firebasestorage.app',
    iosBundleId: 'com.example.camp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtYlx21qrWi4Z-hRIwgyESGvCBLrLFsIY',
    appId: '1:248861591273:web:5bbbc8a59cf09671a99278',
    messagingSenderId: '248861591273',
    projectId: 'camp-ee562',
    authDomain: 'camp-ee562.firebaseapp.com',
    databaseURL: 'https://camp-ee562-default-rtdb.firebaseio.com',
    storageBucket: 'camp-ee562.firebasestorage.app',
  );
}
